/**
 * @file test_guard_rule_corpus.cpp
 * @brief Per-rule positive/negative detection corpus, mechanically ported
 *        from the Go reference's `tests/rules/rules_cases_test.go` (2142
 *        lines) + `tests/rules/helper_test.go`: one-or-more example inputs
 *        per catalog rule (across both `configs/rules.yaml` and
 *        `configs/rules.gitleaks.generated.yaml`), each asserting either an
 *        exact matched span (positive) or zero matches (negative).
 *
 * @details Go harness semantics this file mirrors exactly (read from the Go
 *          source, not invented -- see `helper_test.go`'s
 *          `loadRealConfigScanner` and every `scanner.Scan(...,
 *          []string{ruleID})` / `assertSingleMatch` / `assertNoMatch` call
 *          site in `rules_cases_test.go`):
 *            - both real catalogs are loaded into ONE registry.
 *            - every case scans with the compiled-rule set restricted to
 *              EXACTLY the one rule under test
 *              (`registry.GetCompiledRulesByRuleIDs([]string{ruleID})`),
 *              never the rule's whole data-type group and never the full
 *              registry. Because only one rule is ever active per case, no
 *              cross-rule overlap coalescing occurs anywhere in this corpus
 *              -- resolve_conflicts only ever sees output from a single
 *              rule.
 *            - a positive case asserts `len(matches) == 1` and
 *              `matches[0].FullText` equals the expected span exactly
 *              (`assertSingleMatch`, and the `wantFullText` field of every
 *              `realConfigRuleCases()` entry -- there is no looser "at least
 *              one match" case anywhere in the Go corpus).
 *            - a negative case asserts `len(matches) == 0` (`assertNoMatch`).
 *
 *          The corpus data lives in `tests/data/guard_rule_cases.yaml`,
 *          generated by mechanically replaying the Go source's own string
 *          expressions (concatenation, `strings.Repeat`, the `snilsFormat`/
 *          phone-literal helpers) through a throwaway Go program, then
 *          round-trip-verified byte-for-byte against that Go output -- not
 *          retyped by hand. See task-1.9-report.md for the full derivation
 *          and the case-count reconciliation against the Go file.
 *
 *          Every `text`/`expect_span`/negative string is stored reversed-
 *          then-base64url-encoded (`*_b64` keys, decoded below via
 *          `decode_field`: reverse, then `Utils::Base64::url_decode`) rather
 *          than as plaintext. Many of the ported gitleaks-catalog fixtures
 *          are, by construction, synthetic strings shaped exactly like real
 *          provider secrets (that is the whole point of a secret-detection
 *          corpus) -- committing them as plaintext literals tripped GitHub's
 *          server-side secret-scanning push protection on the first push.
 *          Plain (non-reversed) base64url still tripped a handful of
 *          provider patterns on a second push -- GitHub's scanner appears to
 *          opportunistically base64-decode "looks-like-base64" substrings and
 *          re-match provider regexes against the decoded bytes, which a
 *          straight base64 dump of the corpus satisfies for any fixture that
 *          also happens to resemble a *different* provider's format. The
 *          reversal breaks base64's 4-char/3-byte group alignment, so
 *          decoding the on-disk bytes directly (without first reversing, the
 *          way this loader does) does not reproduce the original plaintext.
 *          Byte-for-byte fidelity against the Go source was round-trip
 *          verified at generation time regardless of the encoding.
 */

#include <algorithm>
#include <cstddef>
#include <memory>
#include <stdexcept>
#include <string>
#include <unordered_set>
#include <vector>

#include <gtest/gtest.h>
#include <yaml-cpp/yaml.h>

#include "guard/Registry.hpp"
#include "guard/Rule.hpp"
#include "guard/RulesYaml.hpp"
#include "guard/Scanner.hpp"
#include "utils/Base64.hpp"

namespace {

struct PositiveCase {
    std::string text;
    std::string expect_span;
    bool has_expect_span = false;
};

struct RuleCorpusEntry {
    std::string rule_id;
    std::vector<PositiveCase> positives;
    std::vector<std::string> negatives;
};

// The two real catalogs shipped in configs/, loaded together -- same pair
// tests/unit/test_guard_rules_yaml.cpp's real_catalog_paths() uses, and the
// same pair the Go harness's loadRealConfigScanner loads.
std::vector<std::string> real_catalog_paths() {
    const std::string root(LLMGUARD_REPO_ROOT);
    return {root + "/configs/rules.yaml", root + "/configs/rules.gitleaks.generated.yaml"};
}

std::string corpus_path() {
    const std::string root(LLMGUARD_REPO_ROOT);
    return root + "/tests/data/guard_rule_cases.yaml";
}

// Corpus strings are stored reversed-then-base64url-encoded (see the
// file-level doc comment): un-reverse, then decode.
std::string decode_field(const YAML::Node& node) {
    std::string encoded = node.as<std::string>();
    std::reverse(encoded.begin(), encoded.end());
    return Utils::Base64::url_decode(encoded);
}

std::vector<RuleCorpusEntry> load_corpus() {
    const YAML::Node root = YAML::LoadFile(corpus_path());
    std::vector<RuleCorpusEntry> out;

    const YAML::Node cases = root["cases"];
    if (!cases || !cases.IsSequence())
        return out;

    out.reserve(cases.size());
    for (const auto& c : cases) {
        RuleCorpusEntry entry;
        entry.rule_id = c["rule_id"].as<std::string>();

        if (const YAML::Node pos = c["positives"]) {
            for (const auto& p : pos) {
                PositiveCase pc;
                pc.text = decode_field(p["text_b64"]);
                if (p["expect_span_b64"]) {
                    pc.expect_span = decode_field(p["expect_span_b64"]);
                    pc.has_expect_span = true;
                }
                entry.positives.push_back(std::move(pc));
            }
        }
        if (const YAML::Node neg = c["negatives_b64"]) {
            for (const auto& n : neg)
                entry.negatives.push_back(decode_field(n));
        }
        out.push_back(std::move(entry));
    }
    return out;
}

// Shared fixture: the real 266-rule registry and the parsed corpus are each
// built once per test *suite* (not per TEST_F) -- compiling 266 RE2 patterns
// and re-parsing (and base64-decoding) a ~100 KB YAML file for every one of
// the TEST_F cases below would multiply this file's runtime for no benefit,
// since none of them mutate either.
class GuardRuleCorpus : public ::testing::Test {
protected:
    static void SetUpTestSuite() {
        auto loaded = Guard::load_rules_files(real_catalog_paths());
        registry_ = Guard::Registry::build(loaded.rules);
        corpus_ = new std::vector<RuleCorpusEntry>(load_corpus());
    }

    static void TearDownTestSuite() {
        registry_.reset();
        delete corpus_;
        corpus_ = nullptr;
    }

    static std::shared_ptr<const Guard::Registry> registry_;
    static std::vector<RuleCorpusEntry>* corpus_;
};

std::shared_ptr<const Guard::Registry> GuardRuleCorpus::registry_;
std::vector<RuleCorpusEntry>* GuardRuleCorpus::corpus_ = nullptr;

}  // namespace

// ── Corpus/catalog cross-checks ───────────────────────────────────────────

TEST_F(GuardRuleCorpus, EveryCorpusRuleIdExistsInTheRealCatalogs) {
    for (const auto& entry : *corpus_) {
        EXPECT_NE(registry_->by_id(entry.rule_id), nullptr)
            << "corpus rule_id '" << entry.rule_id
            << "' not found in the loaded catalogs (configs/rules.yaml + "
               "configs/rules.gitleaks.generated.yaml) -- likely a transcription typo in "
               "tests/data/guard_rule_cases.yaml";
    }
}

TEST_F(GuardRuleCorpus, CorpusCoversEveryLoadedRule) {
    // Mirrors TestRealConfigRuleCases_CoverEveryLoadedRule in the Go
    // reference: every rule the registry knows about must have at least one
    // corpus case, so a rule added to the catalogs without a ported case is
    // caught here instead of shipping silently uncovered.
    std::unordered_set<std::string> covered;
    for (const auto& entry : *corpus_)
        covered.insert(entry.rule_id);

    std::vector<std::string> missing;
    for (const auto& cr : registry_->all()) {
        if (covered.find(cr.rule.id) == covered.end())
            missing.push_back(cr.rule.id);
    }

    std::string joined;
    for (const auto& id : missing) {
        if (!joined.empty())
            joined += ", ";
        joined += id;
    }
    EXPECT_TRUE(missing.empty()) << "rules with no corpus case: " << joined;
}

TEST_F(GuardRuleCorpus, CaseCountsMatchGoReference) {
    // Regression guard pinning the ported totals against the Go source
    // (hand-counted from tests/rules/rules_cases_test.go: 277 entries in
    // realConfigRuleCases() + 70 positive / 34 negative across the ten
    // "extra format scenarios" Test* functions = 381 cases total, spanning
    // all 266 loaded rules). A future edit to the corpus that silently drops
    // or duplicates cases trips this before it trips anything else.
    std::size_t positives = 0;
    std::size_t negatives = 0;
    for (const auto& entry : *corpus_) {
        positives += entry.positives.size();
        negatives += entry.negatives.size();
    }
    EXPECT_EQ(corpus_->size(), 266u);
    EXPECT_EQ(positives, 347u);
    EXPECT_EQ(negatives, 34u);
    EXPECT_EQ(positives + negatives, 381u);
}

// ── Detection: positives / negatives ──────────────────────────────────────

TEST_F(GuardRuleCorpus, PositiveCasesProduceExactlyOneMatchWithExpectedSpan) {
    for (const auto& entry : *corpus_) {
        const Guard::CompiledRule* rule = registry_->by_id(entry.rule_id);
        if (rule == nullptr)
            continue;  // reported by EveryCorpusRuleIdExistsInTheRealCatalogs
        const std::vector<const Guard::CompiledRule*> rules{rule};

        for (const auto& pc : entry.positives) {
            std::vector<Guard::ScanMatch> matches;
            try {
                matches = Guard::scan_rules(pc.text, rules);
            } catch (const std::exception& e) {
                ADD_FAILURE() << "rule '" << entry.rule_id << "': scan_rules threw: " << e.what()
                              << "\n  input: " << pc.text;
                continue;
            }

            if (matches.size() != 1) {
                ADD_FAILURE() << "rule '" << entry.rule_id << "': expected exactly 1 match, got " << matches.size()
                              << "\n  input: " << pc.text;
                for (const auto& m : matches) {
                    ADD_FAILURE() << "    found [" << m.start << "," << m.end
                                  << ") = " << pc.text.substr(m.start, m.end - m.start);
                }
                continue;
            }

            if (pc.has_expect_span) {
                const std::string got = pc.text.substr(matches[0].start, matches[0].end - matches[0].start);
                EXPECT_EQ(got, pc.expect_span) << "rule '" << entry.rule_id
                                                << "': matched span mismatch\n  input: " << pc.text;
            }
        }
    }
}

TEST_F(GuardRuleCorpus, NegativeCasesProduceNoMatch) {
    for (const auto& entry : *corpus_) {
        const Guard::CompiledRule* rule = registry_->by_id(entry.rule_id);
        if (rule == nullptr)
            continue;  // reported by EveryCorpusRuleIdExistsInTheRealCatalogs
        const std::vector<const Guard::CompiledRule*> rules{rule};

        for (const auto& text : entry.negatives) {
            std::vector<Guard::ScanMatch> matches;
            try {
                matches = Guard::scan_rules(text, rules);
            } catch (const std::exception& e) {
                ADD_FAILURE() << "rule '" << entry.rule_id << "': scan_rules threw: " << e.what()
                              << "\n  input: " << text;
                continue;
            }

            if (!matches.empty()) {
                ADD_FAILURE() << "rule '" << entry.rule_id << "': expected no match, got " << matches.size()
                              << "\n  input: " << text;
                for (const auto& m : matches) {
                    ADD_FAILURE() << "    found [" << m.start << "," << m.end
                                  << ") = " << text.substr(m.start, m.end - m.start);
                }
            }
        }
    }
}
